language: php

php:
  - 7.2

# lock distro so new future defaults will not break the build
dist: trusty

before_install:
  - phpenv config-rm xdebug.ini
  - before_script: echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer install

script:
  - ./vendor/bin/phpunit -c phpunit.xml