language: php

php:
  - 7.2

# lock distro so new future defaults will not break the build
dist: trusty

before_install:
  - phpenv config-rm xdebug.ini

before_script:
  - docker-compose -f devops/docker-compose.yml up -d
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

services:
  - docker

install:
  - composer install

script:
  - docker-compose exec redis redis-cli config set notify-keyspace-events K$x
  - ./vendor/bin/phpunit -c phpunit.xml